# Generated by Django 4.2.7 on 2024-04-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, error_messages='ایمیل نا درست است', max_length=254, null=True),
        ),
    ]
