# Generated by Django 4.2.7 on 2023-11-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/%y')),
                ('tag', models.CharField(max_length=9)),
                ('subject', models.CharField(max_length=66)),
                ('body', models.TextField()),
            ],
        ),
    ]
