# Generated by Django 4.2.7 on 2023-11-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(max_length=160),
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(max_length=40),
        ),
    ]
