# Generated by Django 4.2.7 on 2024-04-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/%y')),
                ('title', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=300)),
                ('details', models.TextField()),
                ('customer', models.CharField(max_length=99)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
