# Generated by Django 4.2.7 on 2023-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycv',
            name='img',
            field=models.ImageField(upload_to='cv/templates'),
        ),
    ]
