# Generated by Django 4.2.7 on 2023-11-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_mycv_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycv',
            name='img',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
