# Generated by Django 4.2.7 on 2024-04-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_mycv_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycv',
            old_name='img',
            new_name='main_img',
        ),
        migrations.AddField(
            model_name='mycv',
            name='img_five',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M'),
        ),
        migrations.AddField(
            model_name='mycv',
            name='img_four',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M'),
        ),
        migrations.AddField(
            model_name='mycv',
            name='img_one',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M'),
        ),
        migrations.AddField(
            model_name='mycv',
            name='img_six',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M'),
        ),
        migrations.AddField(
            model_name='mycv',
            name='img_three',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M'),
        ),
        migrations.AddField(
            model_name='mycv',
            name='img_two',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y%m%d%H%M'),
        ),
    ]
