# Generated by Django 4.2.7 on 2024-04-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_rename_img_mycv_main_img_mycv_img_five_mycv_img_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycv',
            name='main_img',
            field=models.ImageField(upload_to='img/%y%m%d%H%M'),
        ),
    ]
